

## Adolescent - Child Sexual Abusers
Onset, End, # of Children and # of Times
```{r fig.width=7, fig.height=3.5, echo=FALSE,  results='asis',dev='svg' }
vars<-c("bhv7a","bhv7b","bhv7c","bhv7d")
labs<-c("Age First \nTouched Child", "Age Last \nTouched Child", "# of Children \nTouched", "# of Times - \nLifetime")
out2<-MeanBox1(vars=vars, labs=labs, data=adolcsa)
if (ncol(out2[[1]])==3) {print(xtable(out2[[1]],align="llrr"  ),type="html",include.rownames=FALSE)}
if (ncol(out2[[1]])==5) {print(xtable(out2[[1]],align="llrrrr"  ),type="html",include.rownames=FALSE)}

out2a<-data.frame(out2[[2]])
out2a$beh <-labs
  if ( table(adolcsa$sex)[1]==0 & table(adolcsa$sex)[2] >0 ) {colnames(out2a)<- c("Male",  "Behavior")}
  if ( table(adolcsa$sex)[1]>0 & table(adolcsa$sex)[2] ==0 ) {colnames(out2a)<- c("Female", "Behavior")}
  if ( table(adolcsa$sex)[1]>0 & table(adolcsa$sex)[2] >0 )  {colnames(out2a)<- c("Male", "Female", "Behavior")}
out3<-melt(out2a, id="Behavior")
g1<-ggplot(out3, aes(x = factor(Behavior, levels=labs), y = value, fill=variable)) +   geom_bar(stat = "identity", position="dodge") +
 	scale_fill_manual(values=c("Navyblue","#007FFF"), name="Gender") +  ylab("Percent") +  xlab("Behavior") + theme_minimal() +  
	geom_text(aes(y=value,   label=round(value,1)), position= position_dodge(width=0.9), vjust=-.5, color="black") +
	scale_y_continuous("Mean",limits=c(0,max(out3$value)*1.1))
g1
```







## Adolescent - Child Sexual Abusers - Amount of Force Used
```{r   echo=FALSE,  results='asis'  }
vars<-c( 'bhv7e1', 'bhv7e2' , 'bhv7e3', 'bhv7e4', 'bhv7e5', 'bhv7e6', 'bhv7e7', 'bhv7e8')
labs<-c( 'Initiated by Child', 'Mutual Consent', 'Promised Toy', 'Tricked Kid', 'Verbal Threat', 'Physical Restraint', 'Physical Aggression', 'Death of Child')
out2<-PercBox1(vars=vars,labs=labs,data=adolcsa)
if (ncol(out2[[1]])==3) {print(xtable(out2[[1]],align="llrr"  ),type="html",include.rownames=FALSE)}
if (ncol(out2[[1]])==5) {print(xtable(out2[[1]],align="llrrrr"  ),type="html",include.rownames=FALSE)}
```



## Adolescent - Child Sexual Abusers - Age & Gender
```{r fig.width=7, fig.height=3.5, echo=FALSE,  results='asis',dev='svg' }
vars<-c( 'bhv7f1', 'bhv7f2' , 'bhv7f3', 'bhv7f4')
labs<-c( 'Girls 3-4 \nYrs Younger', 'Boys 3-4 \nYrs Younger', 'Girls 5+ \nYrs Younger', 'Boys 5+ \nYrs Younger')
out2<-PercBox1(vars=vars,labs=labs,data=adolcsa)
if (ncol(out2[[1]])==3) {print(xtable(out2[[1]],align="llrr"  ),type="html",include.rownames=FALSE)}
if (ncol(out2[[1]])==5) {print(xtable(out2[[1]],align="llrrrr"  ),type="html",include.rownames=FALSE)}
out2a<-data.frame(out2[[2]])
out2a$beh <-labs
  if ( table(adolcsa$sex)[1]==0 & table(adolcsa$sex)[2] >0 ) {colnames(out2a)<- c("Male",  "Behavior")}
  if ( table(adolcsa$sex)[1]>0 & table(adolcsa$sex)[2] ==0 ) {colnames(out2a)<- c("Female", "Behavior")}
  if ( table(adolcsa$sex)[1]>0 & table(adolcsa$sex)[2] >0 )  {colnames(out2a)<- c("Male", "Female", "Behavior")}
out3<-melt(out2a, id="Behavior")
g1<-ggplot(out3, aes(x = factor(Behavior, levels=labs), y = value, fill=variable)) +   geom_bar(stat = "identity", position="dodge") +
 	scale_fill_manual(values=c("Navyblue","#007FFF"), name="Gender") +  ylab("Percent") +  xlab("Behavior") + theme_minimal() +  
	geom_text(aes(y=value,   label=paste0(round(value,1),"%"  )), position= position_dodge(width=0.9), vjust=-.5, color="black") +
	scale_y_continuous("Percent",limits=c(0,max(out3$value)*1.1)) + theme(axis.text=element_text(size=10))
g1
```







## Adolescent - Child Sexual Abusers - Relationship to Victims
```{r fig.width=7, fig.height=3.5, echo=FALSE,  results='asis',dev='svg' }
vars<-c( 'bhv7g1', 'bhv7g2' , 'bhv7g3', 'bhv7g4')
labs<-c( 'Younger Sibling', 'Foster Sibling', 'Other Family', 'Non-Family')
out2<-PercBox1(vars=vars,labs=labs,data=adolcsa)
if (ncol(out2[[1]])==3) {print(xtable(out2[[1]],align="llrr"  ),type="html",include.rownames=FALSE)}
if (ncol(out2[[1]])==5) {print(xtable(out2[[1]],align="llrrrr"  ),type="html",include.rownames=FALSE)}
out2a<-data.frame(out2[[2]])
out2a$beh <-labs
  if ( table(adolcsa$sex)[1]==0 & table(adolcsa$sex)[2] >0 ) {colnames(out2a)<- c("Male",  "Behavior")}
  if ( table(adolcsa$sex)[1]>0 & table(adolcsa$sex)[2] ==0 ) {colnames(out2a)<- c("Female", "Behavior")}
  if ( table(adolcsa$sex)[1]>0 & table(adolcsa$sex)[2] >0 )  {colnames(out2a)<- c("Male", "Female", "Behavior")}
out3<-melt(out2a, id="Behavior")
g1<-ggplot(out3, aes(x = factor(Behavior, levels=labs), y = value, fill=variable)) +   geom_bar(stat = "identity", position="dodge") +
 	scale_fill_manual(values=c("Navyblue","#007FFF"), name="Gender") +  ylab("Percent") +  xlab("Behavior") + theme_minimal() +  
	geom_text(aes(y=value,   label=paste0(round(value,1),"%"  )), position= position_dodge(width=0.9), vjust=-.5, color="black") +
	scale_y_continuous("Percent",limits=c(0,max(out3$value)*1.1))
g1
```


